language: c

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgtest-dev valgrind cmake
  - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
  - tar xf release-1.7.0.tar.gz
  - cd googletest-release-1.7.0
  - cmake -DBUILD_SHARED_LIBS=ON .
  - make
  - sudo cp -a include/gtest /usr/include
  - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
  - sudo apt-get install cppcheck
  - which valgrind
  - cd "${TRAVIS_BUILD_DIR}"
before_script:
  - cmake CMakeLists.txt
  - make
  - cppcheck --force ../
  - valgrind --tool=memcheck --leak-check=full --leak-resolution=med  --track-origins=yes ./unit_test
  - valgrind --tool=memcheck --leak-check=full --leak-resolution=med  --track-origins=yes ./IZ2

